languageCode = "en-us"
title = "Float"
baseURL = "https://jhwncho.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Float documentation for design."
  codePenUser = "Heydon"
