languageCode = "en-us"
title = "Fluid"
baseURL = "https://jhwncho.github.io/float-doc/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Float's building blocks."
  codePenUser = "Heydon"
