languageCode = "en-us"
title = "Float"
baseURL = "https://jhwncho.github.io/float-doc/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Float design system"
  codePenUser = "Heydon"
